### PR TITLE
Remove German strings

### PR DESCRIPTION
**Pull request by imustafin**
There are some German strings in this translation. They need to be removed so that the game  can use the fall-back language for the strings not yet translated to Romanian.

### CODE REVIEW

**Comment by pixeltheman** [comment]
please do

**Review by pixeltheman — APPROVED** [review]
this is necessary

**Review by nomius10 — APPROVED** [review]
Very useful PR. Thanks!

**Comment by nomius10** [comment]
I've performed the merge via my local CLI. I'm closing this PR.

**Pull request closed without merging**
